---
# Exercise for setting up a web server in an EC
- name: Exercise for setting up a web server in an EC 
  # hosts: ubuntu
  # Use the public IP if the VM is already created - 44.192.7.133
  hosts: 54.90.119.89
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  roles:
   - prepare
   - apache